#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjectD.Resource", IsApplication=true)]

namespace ProjectD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000c
			public const int LogIn = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int PassWord = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int SignIn = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int UserName = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int autocomplete_country = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout1 = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout2 = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout3 = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int linearLayout4 = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int linearLayout5 = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int linearLayout6 = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int textView1 = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int textView2 = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int list_item = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SignLogin = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
